server:
  port: 5000
#  servlet:
#    context-path: /test


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ltweb_thymeleaf"
    username: root
    password: Munlatrang.04
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  mandatory-file-encoding: UTF-8
  mail:
    default-encoding: UTF-8
storage.location: C:/uploads